export enum RabbitMQ {
  UsuariosQueue = 'usuarios',
}

export enum UsuariosMSG {
  CREATE = 'CREATE_USUARIO',
  UPDATE = 'UPDATE_USUARIO',
  DELETE = 'DELETE_USUARIO',
  FIND_ALL = 'FIND_USUARIOS',
  FIND_ONE = 'FIND_USUARIO',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  VALIDATE_USER = 'VALIDATE_USER',
  FIND_BY_EMAIL = 'FIND_BY_EMAIL',
  FIND_BY_USERNAME = 'FIND_BY_USERNAME',
}
